<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-72NPBGM" failures="1" tests="7" name="Test" time="34.317" errors="0" timestamp="2022-01-11T17:52:06 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="@BeforeClass setUpClass" time="0.179">
    <failure type="io.cucumber.core.exception.CucumberException" message="Failed to parse &amp;apos;target\failed_test.txt&amp;apos;">
      <![CDATA[io.cucumber.core.exception.CucumberException: Failed to parse 'target\failed_test.txt'
at io.cucumber.core.options.OptionsFileParser.parseFeatureWithLinesFile(OptionsFileParser.java:35)
at io.cucumber.core.options.CucumberOptionsAnnotationParser.addFeatures(CucumberOptionsAnnotationParser.java:136)
at io.cucumber.core.options.CucumberOptionsAnnotationParser.parse(CucumberOptionsAnnotationParser.java:46)
at io.cucumber.testng.TestNGCucumberRunner.<init>(TestNGCucumberRunner.java:85)
at io.cucumber.testng.AbstractTestNGCucumberTests.setUpClass(AbstractTestNGCucumberTests.java:27)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.NoSuchFileException: target\failed_test.txt
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
at java.base/java.nio.file.Files.newInputStream(Files.java:160)
at java.base/java.nio.file.Files.newBufferedReader(Files.java:2922)
at java.base/java.nio.file.Files.readAllLines(Files.java:3412)
at java.base/java.nio.file.Files.readAllLines(Files.java:3453)
at io.cucumber.core.options.OptionsFileParser.parseFeatureWithLinesFile(OptionsFileParser.java:27)
... 17 more
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass setUpClass -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="16.125"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="18.556"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.937"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.925"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.925">
    <failure type="java.lang.AssertionError" message="expected [validation succeeded] but found [validation failed]">
      <![CDATA[java.lang.AssertionError: expected [validation succeeded] but found [validation failed]
at pageObjects.Base_PO.waitForAlert_And_ValidateText(Base_PO.java:71)
at stepDefinitions.LoginSteps.i_should_be_presented_with_the_following_login_validation_message(LoginSteps.java:49)
at âœ½.I should be presented with the following login validation message validation succeeded(classpath:features/Login.feature:24)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="6.264"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.379"/>
</testsuite> <!-- Test -->
