<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-72NPBGM" failures="1" tests="7" name="runners.MainRunner" time="35.074" errors="0" timestamp="2022-01-11T17:49:48 IST" skipped="0">
  <testcase classname="runners.MainRunner" name="runScenario" time="2.978">
    <failure message="expected [validation succeeded] but found [validation failed]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [validation succeeded] but found [validation failed]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at pageObjects.Base_PO.waitForAlert_And_ValidateText(Base_PO.java:71)
at stepDefinitions.LoginSteps.i_should_be_presented_with_the_following_login_validation_message(LoginSteps.java:49)
at âœ½.I should be presented with the following login validation message validation succeeded(classpath:features/Login.feature:24)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runners.MainRunner" name="runScenario" time="3.069"/>
  <system-out/>
  <testcase classname="runners.MainRunner" name="runScenario" time="11.644"/>
  <system-out/>
  <testcase classname="runners.MainRunner" name="runScenario" time="6.142"/>
  <system-out/>
  <testcase classname="runners.MainRunner" name="runScenario" time="5.259"/>
  <system-out/>
  <testcase classname="runners.MainRunner" name="runScenario" time="2.880"/>
  <system-out/>
  <testcase classname="runners.MainRunner" name="runScenario" time="3.102"/>
  <system-out/>
</testsuite> <!-- runners.MainRunner -->
